config/routes.rb
Rails.application.routes.draw do
  resources :families
  resources :gizmos

  root "home#index"
end

app/models/color.rb
class Color
  BPC = 2 # BITS_PER_COLOR = 256

  COLOR_MAP = {
    "n" => "000000",
    "r" => "ff0000",
    "g" => "00ff00",
    "b" => "0000ff",
    "w" => "ffffff"
  }

  attr_accessor :i, :hex_color

  def initialize(i = nil, hex_color = nil)
    if i.kind_of?(String)
      self.h = i
    else
      self.i = i
    end
    self.hex_color = hex_color
  end

  def black?
    i == 0
  end

  def non_black?
    !black
  end

  def non_black
    self unless black?
  end

  def color_value
    i / (BPC * BPC) + ((i / BPC) % BPC) + (i % BPC)
  end

  def contrast
    light? ? BLACK : WHITE
  end

  def h
    hex_color || hex_from_int(@i)
  end

  def h=(h)
    @i = int_from_hex(COLOR_MAP[h.downcase] || h.downcase)
  end

  def light?
    color_value > (BPC-1)*3.0/2
  end

  alias_method :to_i, :i
  alias_method :to_s, :h
#  alias_method :inspect, :h

  def int_from_hex(x)
    x ? x.sub('#','').gsub("00","0").gsub("ff","1").to_i(2) : 0
  end

  private :int_from_hex

  def hex_from_int(x)
    "##{x.to_s(2).rjust(3,'0').gsub("0","00").gsub("1","ff")}"
  end

  private :hex_from_int

  def self.combine(c)
    Color.new(c.map(&:to_i).sum)
  end

  UNLIT = Color.new(0, "#dddddd")
  BLACK = Color.new("n")
  WHITE = Color.new("w")
end

app/models/family.rb
class Family < ActiveRecord::Base
  has_many :gizmos, -> { order(:id) }

  def fill
    @fill ||= Color.combine(gizmos.map(&:fill)).non_black || Color::UNLIT
  end

  def status
    fill.non_black?
  end

  def stroke
    Color::BLACK
  end
end

app/models/gizmo.rb
class Gizmo < ActiveRecord::Base
  belongs_to :family
  validates :name, :presence => true, uniqueness: { scope: :family_id }
  validates :color, :presence => { message: "color is required" }

  delegate :fill, to: :family, prefix: true

  def color=(c)
    @color = Color.new(c)
    self.color_int = @color.to_i
  end

  def color
    @color ||= Color.new(color_int)
  end

  def fill
    status ? color : Color::UNLIT
  end

  def stroke
    color
  end
end

app/models/user.rb
class User
  attr_accessor :valid

  def valid?
    valid
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Authentication
end

app/controllers/concerns/authentication.rb
module Authentication
  def username
    cookies.signed[:user_id]
  end

  def username=(userid)
    cookies.signed[:user_id] = userid
  end

  def mode=(mode)
    cookies.signed[:mode] = mode.to_s
  end

  def edit_mode?
    cookies[:mode] ? cookies.signed[:mode] == "edit" : false
  end

  def can?(action = :view, object = nil)
    action == :create ? edit_mode? : true
  end

  def self.included(base)
    base.helper_method :username
    base.helper_method :can?
  end
end

app/controllers/families_controller.rb
class FamiliesController < ApplicationController
  before_action :set_family, only: [:show, :edit, :update, :destroy]

  # GET /families
  # GET /families.json
  def index
    redirect_to root_url
  end

  # GET /families/1
  # GET /families/1.json
  def show
  end

  # GET /families/new
  def new
    @family = Family.new
  end

  # GET /families/1/edit
  def edit
    @families = Family.all
  end

  # POST /families
  # POST /families.json
  def create
    @family = Family.new(family_params)

    respond_to do |format|
      if @family.save
        format.html { redirect_to families_url, notice: 'Family was successfully created.' }
        format.json { render :show, status: :created, location: @family }
      else
        format.html { render :new }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /families/1
  # PATCH/PUT /families/1.json
  def update
    respond_to do |format|
      if @family.update(family_params)
        format.html { redirect_to families_url, notice: 'Family was successfully updated.' }
        format.json { render :show, status: :ok, location: @family }
      else
        format.html { render :edit }
        format.json { render json: @family.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /families/1
  # DELETE /families/1.json
  def destroy
    @family.destroy
    respond_to do |format|
      format.html { redirect_to families_url, notice: 'Family was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_family
      @family = Family.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def family_params
      params.require(:family).permit(:name, gizmos_attributes: [:id, :name])
    end
end

app/controllers/gizmos_controller.rb
class GizmosController < ApplicationController
  before_action :set_gizmo, only: [:show, :edit, :update, :destroy]

  # GET /gizmos
  # GET /gizmos.json
  def index
    redirect_to root_url
  end

  # GET /gizmos/1
  # GET /gizmos/1.json
  def show
  end

  # GET /gizmos/new
  def new
    @gizmo = Gizmo.new(gizmo_params)
    @families = Family.all
  end

  # GET /gizmos/1/edit
  def edit
    @families = Family.all
  end

  # POST /gizmos
  # POST /gizmos.json
  def create
    @gizmo = Gizmo.new(gizmo_params)

    respond_to do |format|
      if @gizmo.save
        format.html { redirect_to @gizmo.family || @gizmo, notice: 'Gizmo was successfully created.' }
        format.json { render :show, status: :created, location: @gizmo }
      else
        format.html { render :new }
        format.json { render json: @gizmo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gizmos/1
  # PATCH/PUT /gizmos/1.json
  def update
    respond_to do |format|
      if @gizmo.update(gizmo_params)
        format.html { redirect_to @gizmo, notice: 'Gizmo was successfully updated.' }
        format.json { render :show, status: :ok, location: @gizmo }
        format.js
      else
        format.html { render :edit }
        format.json { render json: @gizmo.errors, status: :unprocessable_entity }
      end
    end
    GizmoRelayJob.perform_later(@gizmo) if @gizmo.valid?

  end

  # DELETE /gizmos/1
  # DELETE /gizmos/1.json
  def destroy
    @gizmo.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Gizmo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gizmo
      @gizmo = Gizmo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gizmo_params
      params[:gizmo] ? params.require(:gizmo).permit(:name, :status, :color, :family_id) : {}
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  # GET /families
  # GET /families.json
  def index
    @families = Family.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/families_helper.rb
module FamiliesHelper
end

app/helpers/gizmos_helper.rb
module GizmosHelper
  def gizmo_svg(gizmo = nil)
    fill = gizmo.try(:fill) || "none"
    stroke = gizmo.try(:stroke) || "black"
    name = gizmo.try(:name) || "+"
    raw %{<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"
      width="110px" height="110px">
      <use xlink:href = "#gizmo-outter"/>
      <use xlink:href = "#gizmo-inner" style="fill:#{fill}; stroke:#{stroke};" />
      <text x="55" y="55" class="gizmo-name">#{name}</text>
      </svg>}
  end

  def new_gizmo(attrs = nil)
    attrs = attrs.present? ? {:gizmo => attrs} : {}
    link_to gizmo_svg, new_gizmo_path(attrs), class: "gizmo gizmo-new"
  end
end

app/views/families/_family.html.erb
<div id="family-<%=family.id%>" class="family">
  <%= link_to gizmo_svg(family), edit_family_path(family), class: "family family-edit" %>
</div>

app/views/families/_form.html.erb
<%= form_for(family) do |f| %>
  <%- if family.errors.any? -%>
  <div id="error_explanation">
    <h2><%= pluralize(family.errors.count, "error") %></h2>
    <ul>
      <%- family.errors.full_messages.each do |message| -%>
      <li><%= message %></li>
      <%- end -%>
    </ul>
  </div>
  <%- end -%>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<%- end -%>

app/views/families/edit.html.erb
<%= form_for(@family) do |f| %>
  <h1>
    <%= link_to 'families', root_path %> >
    <%= f.text_field :name %>
    <%= f.submit %>
  </h1>
<% end -%>
<% if @family.errors.any? -%>
<div id="error_explanation">
  <h2><%= pluralize(family.errors.count, "error") %></h2>

  <ul>
    <%- family.errors.full_messages.each do |message| -%>
    <li><%= message %></li>
    <%- end -%>
  </ul>
</div>
<% end -%>

<h2>Gizmos</h2>
<% @family.gizmos.each do |gizmo| -%>
  <%= render 'gizmos/form', gizmo: gizmo %>
<% end -%>

<%= render 'gizmos/form', gizmo: Gizmo.new(:family => @family) %>
<%= link_to 'Cancel', @family %>

app/views/families/new.html.erb
<h1>New Family</h1>

<%= render 'form', family: @family %>

<%= link_to 'Back', root_path %>

app/views/families/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @family %>

app/views/gizmos/_form.html.erb
<%= form_for(gizmo) do |f| %>
  <% if gizmo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gizmo.errors.count, "error") %> prohibited this gizmo from being saved:</h2>

      <ul>
      <% gizmo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <h1>
    <%= link_to 'Families', root_path %> >
    <%= f.collection_select(:family_id, @families, :id, :name) %> >
    <%= f.text_field :name, placeholder: "name" %>
    <%= f.text_field :color, style: "color: #{gizmo.color.contrast}; background-color: #{gizmo.stroke}", placeholder: "color" %>
  </h1>

  <div class="field field-radio" style="background: <%=gizmo.color%>">
    <%= f.check_box :status, style: "color: #{gizmo.color.contrast}; background-color: #{gizmo.stroke}" %>
    <%= f.label :status, "&nbsp;".html_safe %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gizmos/_gizmo.html.erb
<div id="gizmo-<%=gizmo.id%>" class="gizmo-widget">
  <%= form_for gizmo, remote: true, html: {class: "gizmo-widget" } do |f| %>
    <%= f.hidden_field :status, :value => !gizmo.status %>
    <label>
      <%= f.submit "update", style: "display: none" %>
      <%= gizmo_svg(gizmo) %>
    </label>
  <% end %>
</div>

app/views/gizmos/edit.html.erb
<%= render 'form', gizmo: @gizmo %>

app/views/gizmos/new.html.erb
<h1>New Gizmo</h1>

<%= render 'form', gizmo: @gizmo %>

<%= link_to 'Back', root_path %>

app/views/gizmos/show.html.erb
<h1>
  <%= link_to "Families", root_path %> >
  <%- if @gizmo.family -%>
  <%= link_to @gizmo.family.name, family_path(@gizmo.family) %> >
  <%- else -%>
  no family >
  <%- end -%>
  <%= @gizmo.name || "no name" %>
  <small><%= link_to '[Edit]', edit_gizmo_path(@gizmo) %></small>
</h1>
<p id="notice"><%= notice %></p>

<%= render @gizmo %>

app/views/home/_family_and_members.html.erb
<div id="family-and-gizmos-<%=family.id%>" class="family-and-members">
  <%= render family %>
  <div id="family-<%=family.id%>-members" class="family-members">
    <%= render family.gizmos %>
  </div>
  <%- if can?(:create, family.gizmos.new) -%>
    <%= new_gizmo(:family_id => family.id) %>
  <%- end -%>
</div>

app/views/home/index.html.erb
<div id="families">
  <%- @families.each do |family| -%>
    <%= render partial: "family_and_members", locals: { family: family } %>
  <%- end -%>
</div>
<% if can?(:create, Family) -%>
<div>
  <%= link_to gizmo_svg, new_family_path, class: "family family-new" %>
</div>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReachOut</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<!-- images for the pages to use -->
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" style="display:none">
<defs>
  <!-- height / width = 110 -->
  <symbol id="gizmo-outter" viewbox="0 0 200 200">
    <path d="M200 100c-1-10-23-16-26-25-3-10 12-29 6-36-5-8-27 0-34-5-8-6-7-31-16-34-8-3-21 18-31 18-9 0-22-21-31-18s-8 28-15 34c-8 5-29-3-35 5-5 7 9 26 6 36-3 9-25 15-25 25s22 17 25 26-11 28-6 36c6 8 27-1 35 5 7 6 6 30 15 33s22-17 31-17c10 0 22 20 31 17s8-27 16-33c7-6 29 3 34-5 6-8-9-27-6-36s26-16 26-26m-101 70c-36 0-66-31-66-70 0-38 30-69 66-69 37 0 67 31 67 69 0 39-30 70-67 70z" fill-rule="evenodd"/>
  </symbol>
  <symbol id="gizmo-inner" viewbox="0 0 200 200">
    <path d="M100 42c-31 0-56 26-56 58s25 58 56 58c30 0 55-26 55-58s-25-58-55-58m17 35c2 0 5 2 5 5s-3 6-5 6c-3 0-6-3-6-6s3-5 6-5m-34 0c3 0 5 2 5 5s-2 6-5 6-5-3-5-6 2-5 5-5m48 35c-4 13-17 23-31 23s-27-10-32-23c-1-3 1-6 4-7 2-1 6 0 7 3 3 10 11 16 21 16 9 0 18-7 21-16 1-3 4-4 6-3 3 1 5 4 4 7" fill-rule="evenodd"/>
  </symbol>
</defs>
</svg>
<%= yield %>
<footer>
  <div>Sun icon made by <a href="http://www.freepik.com" title="Freepik">Freepik</a> from <a href="http://www.flaticon.com" title="Flaticon">www.flaticon.com</a> is licensed under <a href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0">CC BY 3.0</a></div>
</footer>
</body>
</html>